# Generated by Django 3.1 on 2023-05-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_userjob_profile'),
        ('job_portal', '0004_userjob'),
    ]

    operations = [
    ]
